baseURL = "/"

title = "Nicole Schafer Photo & Film"

enableRobotsTXT = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration   
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

enableEmoji = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
	[languages.de]
		languageName = "DE"
		[[languages.de.menu.main]]
				name = "Startseite"
				url = "/"
				weight = 1
		[[languages.de.menu.main]]
				name = "Dienstleistungen"
				url = "/service"
				weight = 2
		[[languages.de.menu.main]]
				name = "Über mich"
				url = "/about"
				weight = 3
		[[languages.de.menu.main]]
				name = "Kontakt"
				url = "/contact"
				weight = 4
		[[languages.de.menu.main]]
				name = "Kundengalerie"
				url = "https://gallery.nicole-schafer.com/portfolio"
				weight = 5
				post = "noopener"
	[languages.en]
		languageName = "EN"
		[[languages.en.menu.main]]
				name = "Home"
				url = "/"
				weight = 1
		[[languages.en.menu.main]]
				name = "Services"
				url = "/service"
				weight = 2
		[[languages.en.menu.main]]
				name = "About me"
				url = "/about"
				weight = 3
		[[languages.en.menu.main]]
				name = "Contact"
				url = "/contact"
				weight = 4
		[[languages.en.menu.main]]
				name = "Client Gallery"
				url = "https://gallery.nicole-schafer.com/portfolio"
				weight = 5
				post = "noopener"